### PR TITLE
issue 176 GET /api/survey

### PR DESCRIPTION
**Pull request by thaiVL**
- Set up and wrote unit tests for the handler class
- Implemented the SurveyGetAllHandler handler and added the route to hit the handler in the SurveyController
- Documentation of this API can be found in the Google drive.

### CODE REVIEW

**Comment by devamp05** [comment]
Won't you need to add dueDate field to the Survey class and the Survey table in the database for this one? And I also implemented this one.

**Comment by thaiVL** [comment]
> Won't you need to add dueDate field to the Survey class and the Survey table in the database for this one? And I also implemented this one.

I've merged your changes into my branch. My branch now should have dueDate and the Survey object.
I've also fixed all the tests and code that was affected by adding dueDate.

**Review by devamp05 — COMMENTED** [review]
looks good.

**Review by kurtp21 — APPROVED** [review]
Everything looks good to me!

**Pull request merged**
